# Generated by Django 2.2.7 on 2020-04-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_of_the_Code', models.CharField(default='defaultTitle', max_length=120)),
                ('Description_of_the_code', models.TextField(blank=True, null=True)),
                ('Code', models.TextField(blank=True, null=True)),
                ('Upload_Code_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='default_author', max_length=120)),
                ('language', models.CharField(default='default_Language', max_length=120)),
                ('vote', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=1)),
                ('visits', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='resultForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Functionality_Name', models.CharField(max_length=120)),
                ('Programming_Language', models.CharField(max_length=120)),
                ('Author', models.CharField(max_length=120)),
                ('Code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search_page_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchInput', models.CharField(default='defaultTitle', max_length=120)),
            ],
        ),
    ]
