# Generated by Django 2.2.7 on 2020-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_of_the_Code', models.CharField(default='defaultTitle', max_length=120)),
                ('Description_of_the_code', models.TextField(blank=True, null=True)),
                ('Code', models.TextField(blank=True, null=True)),
                ('Upload_Code_file', models.FileField(default='null', upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='default_author', max_length=120)),
                ('language', models.CharField(default='default_Language', max_length=120)),
                ('vote', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=1)),
                ('visits', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CodeInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Action', models.TextField(blank=True)),
                ('locator_type', models.TextField(blank=True, null=True)),
                ('Test_input_value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search_page_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchInput', models.CharField(default='defaultTitle', max_length=120)),
                ('Title_of_the_Code', models.CharField(default='defaultTitle', max_length=120)),
                ('value_desc', models.CharField(default='defaultTitle', max_length=120)),
                ('votes', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='XLUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='xx', max_length=255)),
                ('xl_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
