# Generated by Django 2.2.7 on 2020-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_page_input',
            name='Title_of_the_Code',
            field=models.CharField(default='defaultTitle', max_length=120),
        ),
        migrations.AddField(
            model_name='search_page_input',
            name='value_desc',
            field=models.CharField(default='defaultTitle', max_length=120),
        ),
        migrations.AddField(
            model_name='search_page_input',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='code',
            name='Upload_Code_file',
            field=models.FileField(default='null', upload_to='uploads/'),
        ),
    ]
