# Generated by Django 2.2.7 on 2020-04-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='defaultTitle', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('summery', models.TextField(blank=True, null=True)),
                ('feature', models.BooleanField(default=False)),
                ('First_Name', models.CharField(default='default', max_length=120)),
                ('Last_Name', models.CharField(default='default', max_length=120)),
                ('Email_Address', models.CharField(default='default', max_length=120)),
                ('Gender_Male', models.BooleanField(default=False)),
                ('Gender_Female', models.BooleanField(default=False)),
                ('City', models.CharField(default='default', max_length=120)),
                ('Country', models.CharField(default='india', max_length=120)),
            ],
        ),
    ]
